### ISSUE TITLE
undefined method `end_of_day'

### ISSUE THREAD

**Issue by anandthakker** [rposborne/gitwakatime#3]
Just trying this out, and got the following error.  Don't know enough about Ruby to chase it down, alas...
```
⌘  gitwakatime tally
Mapping commits for dependent commits
Map Completed took 2.330291s
/Users/anand/.rvm/gems/ruby-2.1.5/gems/gitwakatime-0.0.1/lib/gitwakatime/timer.rb:35:in `block in time_params': undefined method `end_of_day' for 2014-12-12 00:00:00 +0100:Time (NoMethodError)
	from /Users/anand/.rvm/gems/ruby-2.1.5/gems/gitwakatime-0.0.1/lib/gitwakatime/timer.rb:31:in `times'
	from /Users/anand/.rvm/gems/ruby-2.1.5/gems/gitwakatime-0.0.1/lib/gitwakatime/timer.rb:31:in `each'
	from /Users/anand/.rvm/gems/ruby-2.1.5/gems/gitwakatime-0.0.1/lib/gitwakatime/timer.rb:31:in `map'
	from /Users/anand/.rvm/gems/ruby-2.1.5/gems/gitwakatime-0.0.1/lib/gitwakatime/timer.rb:31:in `time_params'
	from /Users/anand/.rvm/gems/ruby-2.1.5/gems/gitwakatime-0.0.1/lib/gitwakatime/timer.rb:12:in `initialize'
	from /Users/anand/.rvm/gems/ruby-2.1.5/gems/gitwakatime-0.0.1/lib/gitwakatime/cli.rb:30:in `new'
	from /Users/anand/.rvm/gems/ruby-2.1.5/gems/gitwakatime-0.0.1/lib/gitwakatime/cli.rb:30:in `tally'
	from /Users/anand/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/anand/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/anand/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/anand/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/anand/.rvm/gems/ruby-2.1.5/gems/gitwakatime-0.0.1/bin/gitwakatime:6:in `<top (required)>'
	from /Users/anand/.rvm/gems/ruby-2.1.5/bin/gitwakatime:23:in `load'
	from /Users/anand/.rvm/gems/ruby-2.1.5/bin/gitwakatime:23:in `<main>'
```

**Comment by rposborne** [comment]
This should be fixed.

**Comment by rposborne** [comment]
@anandthakker let me know if you are still having issues.
