### ISSUE TITLE
gitwakatime init failing with "SQLite3::SQLException: no such table: heartbeats (Sequel::DatabaseError)"

### ISSUE THREAD

**Issue by ceilidhboy** [rposborne/gitwakatime#6]
Built fine with Ruby but attempting installation gives the following stack trace:

Traceback (most recent call last):
        37: from /usr/local/bin/gitwakatime:23:in `<main>'
        36: from /usr/local/bin/gitwakatime:23:in `load'
        35: from /var/lib/gems/2.7.0/gems/gitwakatime-0.4.0/bin/gitwakatime:2:in `<top (required)>'
        34: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        33: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        32: from /var/lib/gems/2.7.0/gems/gitwakatime-0.4.0/lib/gitwakatime.rb:16:in `<top (required)>'
        31: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        30: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        29: from /var/lib/gems/2.7.0/gems/gitwakatime-0.4.0/lib/gitwakatime/heartbeat.rb:1:in `<top (required)>'
        28: from /var/lib/gems/2.7.0/gems/gitwakatime-0.4.0/lib/gitwakatime/heartbeat.rb:2:in `<module:GitWakaTime>'
        27: from /var/lib/gems/2.7.0/gems/sequel-5.58.0/lib/sequel/model/base.rb:867:in `inherited'
        26: from /var/lib/gems/2.7.0/gems/sequel-5.58.0/lib/sequel/model/base.rb:606:in `set_dataset'
        25: from /var/lib/gems/2.7.0/gems/sequel-5.58.0/lib/sequel/model/base.rb:819:in `get_db_schema'
        24: from /var/lib/gems/2.7.0/gems/sequel-5.58.0/lib/sequel/model/base.rb:786:in `block in get_db_schema'
        23: from /var/lib/gems/2.7.0/gems/sequel-5.58.0/lib/sequel/model/base.rb:685:in `check_non_connection_error'
        22: from /var/lib/gems/2.7.0/gems/sequel-5.58.0/lib/sequel/database/transactions.rb:195:in `transaction'
        21: from /var/lib/gems/2.7.0/gems/sequel-5.58.0/lib/sequel/database/connecting.rb:269:in `synchronize'
        20: from /var/lib/gems/2.7.0/gems/sequel-5.58.0/lib/sequel/connection_pool/threaded.rb:92:in `hold'
        19: from /var/lib/gems/2.7.0/gems/sequel-5.58.0/lib/sequel/database/transactions.rb:201:in `block in transaction'
        18: from /var/lib/gems/2.7.0/gems/sequel-5.58.0/lib/sequel/model/base.rb:685:in `block in check_non_connection_error'
        17: from /var/lib/gems/2.7.0/gems/sequel-5.58.0/lib/sequel/model/base.rb:786:in `block (2 levels) in get_db_schema'
        16: from /var/lib/gems/2.7.0/gems/sequel-5.58.0/lib/sequel/model/base.rb:242:in `columns'
        15: from /var/lib/gems/2.7.0/gems/sequel-5.58.0/lib/sequel/dataset/actions.rb:76:in `columns'
        14: from /var/lib/gems/2.7.0/gems/sequel-5.58.0/lib/sequel/dataset/actions.rb:86:in `columns!'
        13: from /var/lib/gems/2.7.0/gems/sequel-5.58.0/lib/sequel/dataset/actions.rb:152:in `each'
        12: from /var/lib/gems/2.7.0/gems/sequel-5.58.0/lib/sequel/adapters/sqlite.rb:364:in `fetch_rows'
        11: from /var/lib/gems/2.7.0/gems/sequel-5.58.0/lib/sequel/dataset/actions.rb:1142:in `execute'
        10: from /var/lib/gems/2.7.0/gems/sequel-5.58.0/lib/sequel/adapters/sqlite.rb:156:in `execute'
         9: from /var/lib/gems/2.7.0/gems/sequel-5.58.0/lib/sequel/adapters/sqlite.rb:209:in `_execute'
         8: from /var/lib/gems/2.7.0/gems/sequel-5.58.0/lib/sequel/database/connecting.rb:269:in `synchronize'
         7: from /var/lib/gems/2.7.0/gems/sequel-5.58.0/lib/sequel/connection_pool/threaded.rb:88:in `hold'
         6: from /var/lib/gems/2.7.0/gems/sequel-5.58.0/lib/sequel/adapters/sqlite.rb:216:in `block in _execute'
         5: from /var/lib/gems/2.7.0/gems/sequel-5.58.0/lib/sequel/database/logging.rb:38:in `log_connection_yield'
         4: from /var/lib/gems/2.7.0/gems/sequel-5.58.0/lib/sequel/adapters/sqlite.rb:216:in `block (2 levels) in _execute'
         3: from /var/lib/gems/2.7.0/gems/sqlite3-1.4.4/lib/sqlite3/database.rb:341:in `query'
         2: from /var/lib/gems/2.7.0/gems/sqlite3-1.4.4/lib/sqlite3/database.rb:152:in `prepare'
         1: from /var/lib/gems/2.7.0/gems/sqlite3-1.4.4/lib/sqlite3/database.rb:152:in `new'
/var/lib/gems/2.7.0/gems/sqlite3-1.4.4/lib/sqlite3/database.rb:152:in `initialize': no such table: heartbeats (SQLite3::SQLException)

**Comment by Nick2bad4u** [comment]
Similar issue here:

```
C:/tools/ruby34/lib/ruby/gems/3.4.0/gems/sqlite3-2.9.0-x64-mingw-ucrt/lib/sqlite3/database.rb:167:in 'SQLite3::Database#open_v2': SQLite3::CantOpenException: unable to open database file (Sequel::DatabaseConnectionError)
        from C:/tools/ruby34/lib/ruby/gems/3.4.0/gems/sqlite3-2.9.0-x64-mingw-ucrt/lib/sqlite3/database.rb:167:in 'SQLite3::Database#initialize'
        from C:/tools/ruby34/lib/ruby/gems/3.4.0/gems/sequel-5.101.0/lib/sequel/adapters/sqlite.rb:149:in 'Class#new'
        from C:/tools/ruby34/lib/ruby/gems/3.4.0/gems/sequel-5.101.0/lib/sequel/adapters/sqlite.rb:149:in 'Sequel::SQLite::Database#connect'
        from C:/tools/ruby34/lib/ruby/gems/3.4.0/gems/sequel-5.101.0/lib/sequel/database/connecting.rb:245:in 'Sequel::Database#new_connection'
        from C:/tools/ruby34/lib/ruby/gems/3.4.0/gems/sequel-5.101.0/lib/sequel/connection_pool.rb:163:in 'Sequel::ConnectionPool#make_new'
        from C:/tools/ruby34/lib/ruby/gems/3.4.0/gems/sequel-5.101.0/lib/sequel/connection_pool/timed_queue.rb:134:in 'Sequel::TimedQueueConnectionPool#preallocated_make_new'
        from C:/tools/ruby34/lib/ruby/gems/3.4.0/gems/sequel-5.101.0/lib/sequel/connection_pool/timed_queue.rb:188:in 'Sequel::TimedQueueConnectionPool#try_make_new'
        from C:/tools/ruby34/lib/ruby/gems/3.4.0/gems/sequel-5.101.0/lib/sequel/connection_pool/timed_queue.rb:223:in 'Sequel::TimedQueueConnectionPool#acquire'
        from C:/tools/ruby34/lib/ruby/gems/3.4.0/gems/sequel-5.101.0/lib/sequel/connection_pool/timed_queue.rb:89:in 'Sequel::TimedQueueConnectionPool#hold'
        from C:/tools/ruby34/lib/ruby/gems/3.4.0/gems/sequel-5.101.0/lib/sequel/database/connecting.rb:283:in 'Sequel::Database#synchronize'
        from C:/tools/ruby34/lib/ruby/gems/3.4.0/gems/sequel-5.101.0/lib/sequel/database/connecting.rb:291:in 'Sequel::Database#test_connection'
        from C:/tools/ruby34/lib/ruby/gems/3.4.0/gems/sequel-5.101.0/lib/sequel/database/misc.rb:209:in 'Sequel::Database#initialize'
        from C:/tools/ruby34/lib/ruby/gems/3.4.0/gems/sequel-5.101.0/lib/sequel/adapters/sqlite.rb:116:in 'Sequel::SQLite::Database#initialize'
        from C:/tools/ruby34/lib/ruby/gems/3.4.0/gems/sequel-5.101.0/lib/sequel/database/connecting.rb:54:in 'Class#new'
        from C:/tools/ruby34/lib/ruby/gems/3.4.0/gems/sequel-5.101.0/lib/sequel/database/connecting.rb:54:in 'Sequel::Database.connect'
        from C:/tools/ruby34/lib/ruby/gems/3.4.0/gems/sequel-5.101.0/lib/sequel/core.rb:124:in 'Sequel::SequelMethods#connect'
        from C:/tools/ruby34/lib/ruby/gems/3.4.0/gems/gitwakatime-0.4.0/lib/gitwakatime.rb:4:in '<top (required)>'
        from <internal:C:/tools/ruby34/lib/ruby/site_ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:139:in 'Kernel#require'
        from <internal:C:/tools/ruby34/lib/ruby/site_ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:139:in 'Kernel#require'
        from C:/tools/ruby34/lib/ruby/gems/3.4.0/gems/gitwakatime-0.4.0/bin/gitwakatime:2:in '<top (required)>'
        from C:/tools/ruby34/lib/ruby/site_ruby/3.4.0/rubygems.rb:303:in 'Kernel#load'
        from C:/tools/ruby34/lib/ruby/site_ruby/3.4.0/rubygems.rb:303:in 'Gem.activate_and_load_bin_path'
        from C:/tools/ruby34/bin/gitwakatime:36:in '<main>'
C:/tools/ruby34/lib/ruby/gems/3.4.0/gems/sqlite3-2.9.0-x64-mingw-ucrt/lib/sqlite3/database.rb:167:in 'SQLite3::Database#open_v2': unable to open database file (SQLite3::CantOpenException)
        from C:/tools/ruby34/lib/ruby/gems/3.4.0/gems/sqlite3-2.9.0-x64-mingw-ucrt/lib/sqlite3/database.rb:167:in 'SQLite3::Database#initialize'
        from C:/tools/ruby34/lib/ruby/gems/3.4.0/gems/sequel-5.101.0/lib/sequel/adapters/sqlite.rb:149:in 'Class#new'
        from C:/tools/ruby34/lib/ruby/gems/3.4.0/gems/sequel-5.101.0/lib/sequel/adapters/sqlite.rb:149:in 'Sequel::SQLite::Database#connect'
        from C:/tools/ruby34/lib/ruby/gems/3.4.0/gems/sequel-5.101.0/lib/sequel/database/connecting.rb:245:in 'Sequel::Database#new_connection'
        from C:/tools/ruby34/lib/ruby/gems/3.4.0/gems/sequel-5.101.0/lib/sequel/connection_pool.rb:163:in 'Sequel::ConnectionPool#make_new'
        from C:/tools/ruby34/lib/ruby/gems/3.4.0/gems/sequel-5.101.0/lib/sequel/connection_pool/timed_queue.rb:134:in 'Sequel::TimedQueueConnectionPool#preallocated_make_new'
        from C:/tools/ruby34/lib/ruby/gems/3.4.0/gems/sequel-5.101.0/lib/sequel/connection_pool/timed_queue.rb:188:in 'Sequel::TimedQueueConnectionPool#try_make_new'
        from C:/tools/ruby34/lib/ruby/gems/3.4.0/gems/sequel-5.101.0/lib/sequel/connection_pool/timed_queue.rb:223:in 'Sequel::TimedQueueConnectionPool#acquire'
        from C:/tools/ruby34/lib/ruby/gems/3.4.0/gems/sequel-5.101.0/lib/sequel/connection_pool/timed_queue.rb:89:in 'Sequel::TimedQueueConnectionPool#hold'
        from C:/tools/ruby34/lib/ruby/gems/3.4.0/gems/sequel-5.101.0/lib/sequel/database/connecting.rb:283:in 'Sequel::Database#synchronize'
        from C:/tools/ruby34/lib/ruby/gems/3.4.0/gems/sequel-5.101.0/lib/sequel/database/connecting.rb:291:in 'Sequel::Database#test_connection'
        from C:/tools/ruby34/lib/ruby/gems/3.4.0/gems/sequel-5.101.0/lib/sequel/database/misc.rb:209:in 'Sequel::Database#initialize'
        from C:/tools/ruby34/lib/ruby/gems/3.4.0/gems/sequel-5.101.0/lib/sequel/adapters/sqlite.rb:116:in 'Sequel::SQLite::Database#initialize'
        from C:/tools/ruby34/lib/ruby/gems/3.4.0/gems/sequel-5.101.0/lib/sequel/database/connecting.rb:54:in 'Class#new'
        from C:/tools/ruby34/lib/ruby/gems/3.4.0/gems/sequel-5.101.0/lib/sequel/database/connecting.rb:54:in 'Sequel::Database.connect'
        from C:/tools/ruby34/lib/ruby/gems/3.4.0/gems/sequel-5.101.0/lib/sequel/core.rb:124:in 'Sequel::SequelMethods#connect'
        from C:/tools/ruby34/lib/ruby/gems/3.4.0/gems/gitwakatime-0.4.0/lib/gitwakatime.rb:4:in '<top (required)>'
        from <internal:C:/tools/ruby34/lib/ruby/site_ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:139:in 'Kernel#require'
        from <internal:C:/tools/ruby34/lib/ruby/site_ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:139:in 'Kernel#require'
        from C:/tools/ruby34/lib/ruby/gems/3.4.0/gems/gitwakatime-0.4.0/bin/gitwakatime:2:in '<top (required)>'
        from C:/tools/ruby34/lib/ruby/site_ruby/3.4.0/rubygems.rb:303:in 'Kernel#load'
        from C:/tools/ruby34/lib/ruby/site_ruby/3.4.0/rubygems.rb:303:in 'Gem.activate_and_load_bin_path'
        from C:/tools/ruby34/bin/gitwakatime:36:in '<main>'
```
